// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceParkBackend.Database;

namespace SpaceParkBackend.Migrations
{
    [DbContext(typeof(SpaceparkContext))]
    partial class SpaceparkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceParkBackend.Models.Parkinglot", b =>
                {
                    b.Property<int>("ParkinglotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("StarshipID")
                        .HasColumnType("int");

                    b.HasKey("ParkinglotID");

                    b.HasIndex("StarshipID");

                    b.ToTable("Parkinglots");

                    b.HasData(
                        new
                        {
                            ParkinglotID = 1,
                            Cost = 500,
                            IsOccupied = true,
                            Length = 36,
                            SpaceshipID = 1
                        });
                });

            modelBuilder.Entity("SpaceParkBackend.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarshipID")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            HasPaid = false,
                            Name = "Luke Skywalker",
                            SpaceshipID = 1
                        });
                });

            modelBuilder.Entity("SpaceParkBackend.Models.Starship", b =>
                {
                    b.Property<int>("StarshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StarshipID");

                    b.ToTable("Spaceships");

                    b.HasData(
                        new
                        {
                            SpaceshipID = 1,
                            Length = 32,
                            Name = "Sand Crawler"
                        });
                });

            modelBuilder.Entity("SpaceParkBackend.Models.Parkinglot", b =>
                {
                    b.HasOne("SpaceParkBackend.Models.Starship", "Starship")
                        .WithMany()
                        .HasForeignKey("StarshipID");
                });
#pragma warning restore 612, 618
        }
    }
}
